### ISSUE TITLE
Support for `dockerfile:` in the `build` section of a compose file

### ISSUE THREAD

**Issue by zvin** [balena-io-modules/resin-multibuild#19]
We need to support the dockerfile: entry in the build section of a compose file (currently it will only look in the root of a context)

Builder issue: https://github.com/resin-io/resin-builder/issues/420

**Comment by pdcastro** [comment]
This feature ended up being implemented under a different issue:
#34 [Support dockerfile and context directives in docker-compose](https://github.com/balena-io-modules/resin-multibuild/issues/34)
