### ISSUE TITLE
Support dockerfile and context directives in docker-compose

### ISSUE THREAD

**Issue by CameronDiver** [balena-io-modules/resin-multibuild#34]
We should be able to specify either a context or a dockerfile within the build object in docker-compose.

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_fsyz)

**Comment by pdcastro** [comment]
At least partially implemented by /pull/38 and /pull/41

**Comment by pdcastro** [comment]
This issue remains open because of this bug:
https://github.com/balena-io-modules/resin-bundle-resolve/issues/31
